name: villageapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1
  chewie: ^1.7.1
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  intl: ^0.19.0
  path_provider: ^2.1.1
  cached_network_image: ^3.3.0
  dio: ^5.4.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  image_picker: ^1.0.5
  url_launcher: ^6.2.2
  photo_view: ^0.14.0
  flutter_svg: ^2.0.9
  flutter_image_compress: ^2.1.0
  firebase_app_check: ^0.2.1+8
  shared_preferences: ^2.2.2
  firebase_auth: ^4.15.3
  flutter_launcher_icons: ^0.13.1
  js: ^0.6.7
  
  # UI Enhancement Packages
  animations: ^2.0.8
  flutter_animate: ^4.3.0
  lottie: ^2.7.0
  flutter_card_swiper: ^6.0.0
  smooth_page_indicator: ^1.1.0
  shimmer: ^3.0.0
  flutter_bounce: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/images/middle_school/
    - assets/images/temples/
    - assets/images/streets/
    - assets/images/functions/
    - assets/images/others/
    - assets/images/village_logo.png
    - assets/icons/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
    color: "#FFFFFF"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/village_logo.png"
  adaptive_icon_background: "#FF5722" # Orange color matching the sunset theme
  adaptive_icon_foreground: "assets/images/village_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
