name: villageapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_app_check: ^0.2.1+8
  google_sign_in: ^6.2.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  photo_view: ^0.14.0
  flutter_card_swiper: ^6.0.0
  video_player: ^2.8.1
  chewie: ^1.7.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  path_provider: ^2.1.1
  cached_network_image: ^3.3.0
  dio: ^5.4.0
  image_picker: ^1.0.5
  url_launcher: ^6.2.2
  flutter_image_compress: ^2.1.0
  js: ^0.6.7
  # UI Enhancement Packages
  animations: ^2.0.8
  flutter_animate: ^4.3.0
  shimmer: ^3.0.0
  flutter_bounce: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/middle_school/
    - assets/images/creators/
    - assets/images/festivals/
    - assets/images/functions/
    - assets/images/logos/
    - assets/images/others/
    - assets/images/schools/
    - assets/images/streets/
    - assets/images/temples/
    - assets/icons/
    - assets/animations/
