name: villageapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.8.1
  google_fonts: ^6.1.0
  intl: ^0.18.1
  path_provider: ^2.1.1
  cached_network_image: ^3.3.0
  dio: ^5.3.3
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  image_picker: ^1.0.5
  url_launcher: ^6.2.2
  photo_view: ^0.14.0
  flutter_svg: ^2.0.16
  flutter_image_compress: ^2.1.0
  firebase_app_check: ^0.2.1+8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.8
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/middle_school/
    - assets/images/temples/
    - assets/images/streets/
    - assets/images/functions/
    - assets/images/others/
    - assets/images/village_logo.png
    - assets/icons/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
    color: "#FFFFFF"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
  minimum_ios_deployment_target: '12.0'
