// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABdWpUfH9hhpRru8OOiX6V1ot7xRMcxeI',
    appId: '1:660862490649:web:6240ff22aa45414ce3f288',
    messagingSenderId: '660862490649',
    projectId: 'village-645a1',
    authDomain: 'village-645a1.firebaseapp.com',
    storageBucket: 'village-645a1.firebasestorage.app',
    measurementId: 'G-REYYLYP49Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5UQxpED8y1a_l37pAuqhZ1qNKasP729M',
    appId: '1:660862490649:android:7b6065d87c9d039be3f288',
    messagingSenderId: '660862490649',
    projectId: 'village-645a1',
    storageBucket: 'village-645a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe7w0woEMdIWMSprcwbE3KwmQ1AyhHDpE',
    appId: '1:660862490649:ios:7962eea2e3ed1e15e3f288',
    messagingSenderId: '660862490649',
    projectId: 'village-645a1',
    storageBucket: 'village-645a1.firebasestorage.app',
    iosBundleId: 'com.example.villageapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe7w0woEMdIWMSprcwbE3KwmQ1AyhHDpE',
    appId: '1:660862490649:ios:7962eea2e3ed1e15e3f288',
    messagingSenderId: '660862490649',
    projectId: 'village-645a1',
    storageBucket: 'village-645a1.firebasestorage.app',
    iosBundleId: 'com.example.villageapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABdWpUfH9hhpRru8OOiX6V1ot7xRMcxeI',
    appId: '1:660862490649:web:a0bf65be8a4c4d15e3f288',
    messagingSenderId: '660862490649',
    projectId: 'village-645a1',
    authDomain: 'village-645a1.firebaseapp.com',
    storageBucket: 'village-645a1.firebasestorage.app',
    measurementId: 'G-E9MQL3WT8L',
  );
}
